baseurl: /warc-specifications

markdown: kramdown

permalink: pretty

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

